export const DEFAULT_DATA = [
  { name: 'Obediencia', isSelected: false },
  { name: 'Humildad', isSelected: false },
  { name: 'Misericordia', isSelected: false },
  { name: 'Bondad', isSelected: false },
  { name: 'Justicia', isSelected: false },
  { name: 'Gloria', isSelected: false },
  { name: 'Amor', isSelected: false },
  { name: 'Naturaleza divina', isSelected: false },
  { name: 'Piedad', isSelected: false },
  { name: 'Fuerza', isSelected: false },
  { name: 'Autoridad', isSelected: false },
  { name: 'Poder y capacidad de afirmación', isSelected: false },
  { name: 'Poder y capacidad de fortalecer', isSelected: false },
  { name: 'Poder y capacidad de convencimiento', isSelected: false },
  { name: 'Poder y capacidad de salvar', isSelected: false },
  { name: 'Poder y capacidad de reconciliación', isSelected: false },
  { name: 'Poder Creativo', isSelected: false },
];